# Generated by Django 4.0 on 2022-02-25 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_cid', models.IntegerField()),
                ('patient_name', models.TextField()),
                ('patient_age', models.IntegerField()),
                ('Diagonisis', models.TextField()),
                ('Description', models.TextField()),
                ('Medicine', models.TextField()),
                ('Doctor', models.TextField()),
            ],
        ),
    ]
